### ISSUE TITLE
Fiddle Output Safari

### ISSUE THREAD

**Issue by leandrobrunner** [sveltosis/sveltosis#1]
Fiddle output is not working in Safari (MacOS / iPadOS / iOS).

![image](https://user-images.githubusercontent.com/1664991/192117569-f59145e3-5913-48d9-86a4-9b6aea4e1f01.png)

![image](https://user-images.githubusercontent.com/1664991/192117870-58b13c79-55bd-4e3b-94a3-91e695217d6e.png)

**Comment by raymondmuller** [comment]
@leandrobrunner Thanks for opening the issue 👍 

A regular expression in the parser was using **lookbehind**, which doesn't seem supported by Safari (https://caniuse.com/?search=lookbehind). This has been fixed now.
