### ISSUE TITLE
parser: else-if should also prepend state

### ISSUE THREAD

**Issue by raymondmuller** [sveltosis/sveltosis#23]
_FAIL packages/parser/test/if-else.test.ts > if / else
AssertionError: expected '5 > x' to deeply equal '5 > state.x'
Test Files 1 failed | 5 passed (6)
Tests 1 failed | 11 passed (12)

Expected "5 > state.x"
Received "5 > x"_

**Comment by ajanes93** [comment]
Fixed by #24
